import { BasicColumn, FormSchema } from '/@/components/Table'
import { getDictTextByCode } from '/@/utils/dict'
import { getAreaTree } from './enterprise.api'

export const columns: BasicColumn[] = [
  {
    title: '企业名称',
    dataIndex: 'name',
    width: 300,
  },
  {
    title: '区域',
    dataIndex: 'areaName',
    width: 140,
  },
  {
    title: '部门',
    dataIndex: 'departName',
    width: 140,
  },
  {
    title: '企业类型（矿山）',
    dataIndex: 'mineType',
    width: 140,
    customRender: ({ value }) => getDictTextByCode(value, 'mine_speciality') || value || '-',
  },
  {
    title: '企业编码（矿山）',
    dataIndex: 'mineId',
    width: 140,
  },
  {
    title: '生产状态',
    dataIndex: 'productionStatus',
    width: 120,
    customRender: ({ value }) => getDictTextByCode(value, 'mine_product_status') || value || '-',
  },
  {
    title: '日常监管主体',
    dataIndex: 'rcjgzt',
    width: 140,
  },
  {
    title: '上次填报时间',
    dataIndex: 'operationDatetime',
    width: 180,
  },
  {
    title: '审核状态',
    dataIndex: 'checkStateText',
    width: 120,
  },
]

export const searchFormSchema: FormSchema[] = [
  {
    field: 'areaId',
    label: '区域',
    component: 'ApiTreeSelect',
    colProps: { span: 4 },
    componentProps: {
      api: getAreaTree,
      resultField: 'children',
      fieldNames: { label: 'label', value: 'value', children: 'children' },
      treeDefaultExpandAll: true,
      placeholder: '请选择区域',
      allowClear: true,
    },
  },
  {
    field: 'speciality',
    label: '企业类型',
    component: 'JDictSelectTag',
    colProps: { span: 5 },
    componentProps: {
      dictCode: 'mine_speciality',
      placeholder: '请选择企业类型',
      allowClear: true,
    },
  },
  {
    field: 'productionStatus',
    label: '生产状态',
    component: 'JDictSelectTag',
    colProps: { span: 4 },
    componentProps: {
      dictCode: 'mine_product_status',
      mode: 'multiple',
      placeholder: '请选择生产状态',
      allowClear: true,
      showChooseOption: false,
    },
  },
  {
    field: 'checkState',
    label: '审核状态',
    component: 'Select',
    colProps: { span: 4 },
    componentProps: {
      options: [
        { label: '待提交', value: '01' },
        { label: '审核中', value: '02' },
        { label: '退回', value: '03' },
        { label: '审核通过', value: '04' },
      ],
      placeholder: '请选择审核状态',
      allowClear: true,
    },
  },
  {
    field: 'name',
    label: '企业名称',
    component: 'Input',
    colProps: { span: 4 },
    componentProps: { placeholder: '请输入企业名称' },
  },
]

/** mock 列表数据 */
export const mockListData = {
  records: [
    {
      id: 'mock-001',
      name: '永靖县盛达煤矿有限公司',
      mineId: 'MINE-YJX-0001',
      meTyshxydm: '91620122MA6ABCDE12',
      mineType: '2',
      areaId: '620122',
      areaName: '永靖县',
      rcjgzt: '永靖县应急管理局',
      operationDatetime: '2026-03-01 10:20:00',
      checkStateText: '审核通过',
      legalName: '张伟',
      legalPhone: '13909301001',
      directorName: '刘强',
      directorPhone: '13909301002',
      contactsPhone: '0930-8888888',
      productionStatus: '01',
      address: '甘肃省临夏回族自治州永靖县工业园区矿山路8号',
      buildMineDate: '2008-03-15',
      productDate: '2009-09-01',
      industry: '煤炭',
      companyEconomyType: '有限责任公司',
      safeManageOrgName: '安全生产管理部',
      fullTimeSafePersonCount: 8,
      safeDirectorName: '王磊',
      safeDirectorPhone: '13909301003',
      contacts: '陈明',
      contactsMailbox: 'chenming@yjxmine.com',
      seniorManagementCount: 5,
      professionalTechniciansCount: 15,
      specialOperationPersonCount: 30,
      employeesCount: 200,
      longitude: 103.317520,
      latitude: 35.940130,
      postalCode: '731600',
      // 安全许可证信息
      safeLicenceDTO: {
        aqxkzLicenceNumber: 'AQ-2024-YJX-0001',
        aqxkzStartDate: '2024-01-01',
        aqxkzExpiresDate: '2027-01-01',
        aqxkzIssuanceOrg: '甘肃省应急管理厅',
        aqxkzFirstCertificatesDate: '2009-09-01',
        aqxkzBusinessNature: '开采煤矿',
      },
    },
  ],
  total: 1,
  size: 20,
  current: 1,
}

/** mock 详情数据 */
export const mockDetailData = {
  id: 'mock-001',
  name: '永靖县盛达煤矿有限公司',
  mineId: 'MINE-YJX-0001',
  meTyshxydm: '91620122MA6ABCDE12',
  mineType: '2',
  areaId: '620122',
  areaName: '永靖县',
  rcjgzt: '永靖县应急管理局',
  operationDatetime: '2026-03-01 10:20:00',
  checkStateText: '审核通过',
  legalName: '张伟',
  legalPhone: '13909301001',
  directorName: '刘强',
  directorPhone: '13909301002',
  contactsPhone: '0930-8888888',
  productionStatus: '01',
  address: '甘肃省临夏回族自治州永靖县工业园区矿山路8号',
  buildMineDate: '2008-03-15',
  productDate: '2009-09-01',
  industry: '煤炭',
  companyEconomyType: '有限责任公司',
  safeManageOrgName: '安全生产管理部',
  fullTimeSafePersonCount: 8,
  safeDirectorName: '王磊',
  safeDirectorPhone: '13909301003',
  contacts: '陈明',
  contactsMailbox: 'chenming@yjxmine.com',
  seniorManagementCount: 5,
  professionalTechniciansCount: 15,
  specialOperationPersonCount: 30,
  employeesCount: 200,
  longitude: 103.317520,
  latitude: 35.940130,
  postalCode: '731600',
  safeLicenceDTO: {
    aqxkzLicenceNumber: 'AQ-2024-YJX-0001',
    aqxkzStartDate: '2024-01-01',
    aqxkzExpiresDate: '2027-01-01',
    aqxkzIssuanceOrg: '甘肃省应急管理厅',
    aqxkzFirstCertificatesDate: '2009-09-01',
    aqxkzBusinessNature: '开采煤矿',
  },
}
